### ISSUE TITLE
关于子目录大量数据菜单展开收缩卡顿（超级卡顿）问题的反馈

### ISSUE THREAD

**Issue by Amos-research9725** [TinyWisp/vue-tree#2]
![image](https://user-images.githubusercontent.com/56807418/147723415-08ecaefe-7a2b-48bf-90a8-1c89e36850b6.png)
![image](https://user-images.githubusercontent.com/56807418/147723506-b675aa5c-6ebe-4a5c-83e9-5e0a399e40f4.png)

**Comment by TinyWisp** [comment]
你好，在2.0.0版本中，我把展开/折叠优化了下。
麻烦试下2.0.0，并加上:animationDuration="0"属性。
