### ISSUE TITLE
hasChild 设置为false，可以通过拖拽让hasChild:false 失效 ？

### ISSUE THREAD

**Issue by Atwen** [TinyWisp/vue-tree#3]
![image](https://user-images.githubusercontent.com/76642875/179877669-174161cf-586e-4ec5-9b25-a78f9e66f22e.png)
![image](https://user-images.githubusercontent.com/76642875/179877748-6ce0a287-050b-4af6-a8f2-512dcac34956.png)

**Comment by Atwen** [comment]
怎样做到让一个结点始终没有child呢，也就是不可以通过拖拽往这个结点添加子结点呢？

**Comment by TinyWisp** [comment]
hasChild是表示某节点是否有子节点，拖曳操作后，节点的位置发生变化，可能从没有子节点变为有子节点，从有子节点变为没有子节点，因此hasChild会发生变化。

**Comment by Atwen** [comment]
> hasChild是表示某个节点有节点节点运行后，发生了拖曳节点发生变化，因此发生了节点节点的变化，因此发生了节点节点的变化。

**Comment by Atwen** [comment]
> hasChild是表示某节点是否有子节点，拖曳操作后，节点的位置发生变化，可能从没有子节点变为有子节点，从有子节点变为没有子节点，因此hasChild会发生变化。



> hasChild是表示某节点是否有子节点，拖曳操作后，节点的位置发生变化，可能从没有子节点变为有子节点，从有子节点变为没有子节点，因此hasChild会发生变化。

好的，明白了，谢谢。
