### ISSUE TITLE
is vue-tree-methods documentation correct?

### ISSUE THREAD

**Issue by yureckey** [TinyWisp/vue-tree#6]
Hi there.
Thank you for your work.
I'm trying to use it in my project, I noted that this documentation
https://github.com/TinyWisp/vue-tree/wiki/Document#vue-tree-methods
isn't quite correct.
For example, it has method getNode, while actual library doesn't have it but have getById.
Maybe I'm looking the wrong place for documentation?

**Comment by TinyWisp** [comment]
Thank you for pointing out the error!  I corrected it in the document.
