### ISSUE TITLE
layout breaks when parent container have transform

### ISSUE THREAD

**Issue by yureckey** [TinyWisp/vue-tree#7]
I'm trying to use vue-tree in widget library, in the sidebar element. So, my sidebar container have
transform: translate3d(0, 0, 0);
this seem affect vue-tree. When I drag elements, arrow and element name are shown way off their normal positions.
You can recreate by adding     transform: translate3d(0, 0, 0); in your sample code in div .example-wrapper
Is there some easy fix/workaround (besides "transform:unset")?

**Comment by TinyWisp** [comment]
try the 3.2.0 version,  I fixed this problem.

**Comment by yureckey** [comment]
It did fixed it, thank you very much!
