### ISSUE TITLE
titleMaxWidth with negative values only works for percents

### ISSUE THREAD

**Issue by yureckey** [TinyWisp/vue-tree#8]
Maybe I'm doing something wrong, but even for built-in sample
https://tinywisp.github.io/vue-tree/#/en/example/custom-appearance/limit-title-width
negative titleMaxWidth only works when set to %, but it's not working with 'px' or 'rem' which it should according to doc [titleMaxWidth](https://github.com/TinyWisp/vue-tree/wiki/Document#titlemaxwidth)

**Comment by TinyWisp** [comment]
I fixed it in version 3.2.1

**Comment by yureckey** [comment]
Thanks for swift response and fix!
