### ISSUE TITLE
can't see tooltips on items with truncated text

### ISSUE THREAD

**Issue by yureckey** [TinyWisp/vue-tree#9]
I'm not sure how it should work, but I was expecting when title is truncated due to titleMaxWidth then there should be tooltip when mouse is over (with certain delay, obviously). But I don't see any tooltip

**Comment by TinyWisp** [comment]
I fixed it in the version 3.2.2

**Comment by yureckey** [comment]
Once again thanks for super quick fix. Can you adjust it some more, though? Currently, tooltip won't show if there is small number (one or two, I didn't tested thoroughly) of clipped symbols. Is that by design?

**Comment by TinyWisp** [comment]
I cannot reproduce what you said.  It is not by design.
A node's tooltip shows when the mouse is over and the expression `titleElement.offsetWidth < titleElement.scrollWidth` is true.

**Comment by yureckey** [comment]
here is sample to reproduce
https://codepen.io/yureckey/pen/jOdoaYr
the first item doesn't give tooltip

**Comment by TinyWisp** [comment]
> here is sample to reproduce https://codepen.io/yureckey/pen/jOdoaYr the first item doesn't give tooltip

Your sample works all right in firefox, while in chrome the first node of the tree doesn't show the tooltip.
It might be a browser relative problem. it is really wierd that the first node's text is truncated, while its offsetWidth property is equal to its scrollWidth property. I don't know why.

I think you can change the font-family property to avoid this problem.

example
```css
.tree {
  width: 400px;
  font-family: Arial;
}
```

**Comment by yureckey** [comment]
Ah, right, I only tested in Chrome. Thanks for workaround, I'll check it
